### ISSUE TITLE
Timed Out Error. 

### ISSUE THREAD

**Issue by ghost** [confluentinc/confluent-kafka-go#434] opened 2020-03-04 05:42 UTC
Description
===========
I am running a service that will take multiple CSV files and it spawns the goroutine for each and every CSV file. 
It will do some preprocessing and push it to Kafka which is running as a broker.

But I am seeing following issue after which my server got aborted

``` Timed out 0 in-flight, 5 retry-queued, 0 out-queue, 0 p$rtially-sent requests
*** rdkafka_buf.c:199:rd_kafka_bufq_deq: assert: rd_atomic32_get(&rkbufq->rkbq_cnt) > 0 ***
```

How to reproduce
================
Multiple go routine and every go routine writing to kafka, acting as producer

Checklist
=========
Please provide the following information:

 - [ ] confluent-kafka-go and librdkafka version (`LibraryVersion(1.3)`):
 - [ ] Apache Kafka broker version: 2.12
 - [ ] Client configuration: `ConfigMap{...}`
 - [ ] Operating system: amazon linux
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by edenhill** [comment] 2020-03-04 06:48
Interesting, we need more information.
Can you reproduce this with `"debug": "all"` configured and provide the logs?
Also, it would be good to see the source code of the relevant parts of your application, the parts that interact with the Go client.

**Comment by milindl** [comment] 2024-03-05 13:01
Closing this as it's been a while since this has been awaiting the information that Magnus asked for.
If this still persists, please reopen with the debug logs and relevant source code.

**Closed by milindl** 2024-03-05 13:01 UTC
