### ISSUE TITLE
consumer: Close() blocks indefinitely

### ISSUE THREAD

**Issue by agis** [confluentinc/confluent-kafka-go#65] opened 2017-05-26 14:34 UTC
Hello.

I'm using confluent-kafka-go 0.9.4 with librdkafka 0.9.5 on MacOS. I create two consumers consuming from the same topic and all is fine until I call `Close()` on them, which blocks forever on: https://github.com/confluentinc/confluent-kafka-go/blob/v0.9.4/kafka/consumer.go#L255

Debug logs:

```shell
# ...
%7|1495808566.326|CGRPTERM|rdkafka#consumer-2| [thrd:main]: Terminating group "127.0.0.1" in state up with 1 partition(s)
%7|1495808566.326|CGRPTERM|rdkafka#consumer-1| [thrd:main]: Terminating group "127.0.0.1" in state up with 1 partition(s)
%7|1495808566.326|UNSUBSCRIBE|rdkafka#consumer-2| [thrd:main]: Group "127.0.0.1": unsubscribe from current subscription of 1 topics (leave group=yes, join sta
te wait-revoke-rebalance_cb, v4)
%7|1495808566.326|UNSUBSCRIBE|rdkafka#consumer-1| [thrd:main]: Group "127.0.0.1": unsubscribe from current subscription of 1 topics (leave group=yes, join sta
te wait-revoke-rebalance_cb, v4)
%7|1495808566.326|SUBSCRIPTION|rdkafka#consumer-2| [thrd:main]: Group "127.0.0.1": clearing subscribed topics list (1)
%7|1495808566.326|SUBSCRIPTION|rdkafka#consumer-1| [thrd:main]: Group "127.0.0.1": clearing subscribed topics list (1)
%7|1495808566.326|SUBSCRIPTION|rdkafka#consumer-2| [thrd:main]: Group "127.0.0.1": effective subscription list changed from 1 to 0 topic(s):
%7|1495808566.326|SUBSCRIPTION|rdkafka#consumer-1| [thrd:main]: Group "127.0.0.1": effective subscription list changed from 1 to 0 topic(s):
%7|1495808566.326|CGRPTERM|rdkafka#consumer-2| [thrd:main]: Group "127.0.0.1": waiting for rebalance_cb, 1 toppar(s), 0 unassignment(s), 0 commit(s), wait-una
ssign flag, (state up, join-state wait-revoke-rebalance_cb) before terminating
%7|1495808566.326|CGRPTERM|rdkafka#consumer-1| [thrd:main]: Group "127.0.0.1": waiting for rebalance_cb, 1 toppar(s), 0 unassignment(s), 0 commit(s), wait-una
ssign flag, (state up, join-state wait-revoke-rebalance_cb) before terminating
%7|1495808566.326|CGRPTERM|rdkafka#consumer-2| [thrd:main]: Group "127.0.0.1": waiting for rebalance_cb, 1 toppar(s), 0 unassignment(s), 0 commit(s), wait-una
ssign flag, (state up, join-state wait-revoke-rebalance_cb) before terminating
%7|1495808566.326|CGRPTERM|rdkafka#consumer-1| [thrd:main]: Group "127.0.0.1": waiting for rebalance_cb, 1 toppar(s), 0 unassignment(s), 0 commit(s), wait-una
ssign flag, (state up, join-state wait-revoke-rebalance_cb) before terminating
%7|1495808566.420|CGRPTERM|rdkafka#consumer-1| [thrd:main]: Group "127.0.0.1": waiting for rebalance_cb, 1 toppar(s), 0 unassignment(s), 0 commit(s), wait-una
ssign flag, (state up, join-state wait-revoke-rebalance_cb) before terminating
%7|1495808566.610|CGRPTERM|rdkafka#consumer-2| [thrd:main]: Group "127.0.0.1": waiting for rebalance_cb, 1 toppar(s), 0 unassignment(s), 0 commit(s), wait-una
ssign flag, (state up, join-state wait-revoke-rebalance_cb) before terminating
%7|1495808567.424|CGRPTERM|rdkafka#consumer-1| [thrd:main]: Group "127.0.0.1": waiting for rebalance_cb, 1 toppar(s), 0 unassignment(s), 0 commit(s), wait-una
ssign flag, (state up, join-state wait-revoke-rebalance_cb) before terminating
%7|1495808567.613|CGRPTERM|rdkafka#consumer-2| [thrd:main]: Group "127.0.0.1": waiting for rebalance_cb, 1 toppar(s), 0 unassignment(s), 0 commit(s), wait-una
ssign flag, (state up, join-state wait-revoke-rebalance_cb) before terminating
%7|1495808568.425|CGRPTERM|rdkafka#consumer-1| [thrd:main]: Group "127.0.0.1": waiting for rebalance_cb, 1 toppar(s), 0 unassignment(s), 0 commit(s), wait-una
ssign flag, (state up, join-state wait-revoke-rebalance_cb) before terminating
# ... (goes on forever)
```

librdkafka configuration:
```json
{
 "api.version.request": true,
 "bootstrap.servers": "foo-bar.com",
 "log.connection.close": false,
 "session.timeout.ms": 6000,
 "go.events.channel.enable": true,
 "go.application.rebalance.enable": true,
 "enable.auto.commit": false,
 "debug": "cgrp,topic,protocol"
}
```

Setting `go.events.channel.enable` to `false` makes `Close()` proceed. However I'm calling `Assign()` and `Unassign()` properly in the consumer loop (as demonstrated in the examples).

This also doesn't happen with a single consumer. It seems that it's the rebalancing that causes this.

Any ideas?

Thanks in advance.

**Comment by agis** [comment] 2017-06-19 09:54
@edenhill Any insights on this one?

**Comment by edenhill** [comment] 2017-06-20 08:59
Thanks for your report, will investigate.

**Comment by agis** [comment] 2017-06-26 10:21
@edenhill I've added a stripped-down script that reproduces the issue: https://github.com/agis/confluent-kafka-go-GH64. I've also added logging output from librdkafka and the script itself in case of a [successful](https://github.com/agis/confluent-kafka-go-GH64/blob/master/successful.log) and [unsuccessful]((https://github.com/agis/confluent-kafka-go-GH64/blob/master/unsuccessful.log)) run in the repository.

The failures are non-deterministic, it might takes 6 or 7 runs to hit the issue.

The topic used is the following (we're on a 3-node cluster):

```
Topic:test-foo  PartitionCount:4        ReplicationFactor:1     Configs:
        Topic: test-foo Partition: 0    Leader: 1       Replicas: 1     Isr: 1
        Topic: test-foo Partition: 1    Leader: 2       Replicas: 2     Isr: 2
        Topic: test-foo Partition: 2    Leader: 3       Replicas: 3     Isr: 3
        Topic: test-foo Partition: 3    Leader: 1       Replicas: 1     Isr: 1
```

Note that this only seems to happen while also producing, so that there are actual messages to consume and also `CommitOffsets()` is called.

I produce using the console producer:

```bash
while true
do
        sleep 0.5
        cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1 | kafka console-producer --topic test-foo --sync
done
```

**Comment by agis** [comment] 2017-07-05 13:26
@edenhill Going a little bit deeper, it seems that this happens when `eventPoll()` receives a `RevokedPartition` event from librdkafka and the user calls `Close()` _before_ consuming the event and calling `Unassign()`.

This makes sense after reading the relevant comment [here](https://github.com/confluentinc/confluent-kafka-go/blob/0.9.4.x/kafka/event.go#L126-L138):

> [...] since librdkafka requires the rebalance event to be "acked" by
> the application to synchronize state we keep track of if the
> application performed assign() or unassign(), but this only works for
> the non-channel case. for the channel case we assume the application
> calls assign() / unassign().
> failure to do so will "hang" the consumer, e.g., it wont start consuming
> and it wont close cleanly, so this error case should be visible
> immediately to the application developer.

This may happen if the events channel is buffered, since `eventPoll()` will just [immediately insert](https://github.com/confluentinc/confluent-kafka-go/blob/0.9.4.x/kafka/event.go#L267) the `RevokedPartition` event to the channel (because it's buffered) and continue polling, regardless if the user has ACKed the event.

This means that while `Close()` [waits for the `consumerReader()` to terminate](https://github.com/confluentinc/confluent-kafka-go/blob/0.9.4.x/kafka/consumer.go#L248), it isn't guaranteed that the user have called `Unassign()` just yet.

I'm not sure if that makes sense and if it could be solved without avoid using the events channel (or at least turning `go.application.rebalance.enable` to `false`).

**Comment by edenhill** [comment] 2017-08-09 09:40
What if Close() would terminate the consumerReader and then read all remaining events on the c.Events() queue, specifically handling rebalance events to synchronize state with librdkafka, but hiding it all from the application?

**Comment by BDeus** [comment] 2018-02-07 16:53
Any news about this issue?
Same problem here with the channel consumer.

**Comment by edenhill** [comment] 2018-02-14 20:06
Need to construct a small test-case that reproduces this every time,
if anyone has some spare cycles for this we'd be very happy.

**Comment by JeanMertz** [comment] 2018-02-24 18:39
I am seeing the same behaviour. Unfortunately I don't have a small test-case to put here yet. If I find anything else, or have the time to reduce the current problem to a small case, I'll report back.

**Comment by JeanMertz** [comment] 2018-02-26 09:05
Update: I believe my use-case is actually a combination of this one, and https://github.com/confluentinc/confluent-kafka-go/issues/55.

In my case, I send a received message to an internal blocking channel. If no receiver is on the other end of that channel, the event queue can't be processed, and thus any unassign request is buffered and not executed.

When trying to terminate the consumer, the `Close()` function blocks endlessly on this message:

```
%7|1519635082.564|CGRPTERM|rdkafka#consumer-2| [thrd:main]: Group "TestMessage_Ack-92813": waiting for rebalance_cb, 1 toppar(s), 0 unassignment(s), 0 commit(s), wait-unassign flag, (state up, join-state wait-revoke-rebalance_cb) before terminating
```

Obviously, because of the stuck event queue, the unassignment will never happen, which in turn means the consumer can never close its connection.

I could switch to a buffered channel, but that has its own set of problems, a more manageable solution would be to be able to handle events and messages on separate channels, where a queue on one (messages) is acceptable, but a (blocking) queue on the other (handling toppar assignment/unassignment) is not.

**Comment by eliaslevy** [comment] 2018-05-27 16:01
Just hit what seems to be a related issue.  Our consumer by default is configured to panic if there aren't previous committed starting offsets for the partitions it is assigned.  This is a failsafe measure to make sure a consumer is not started unexpectedly in an environment.

The consumer, using the channel API variant, calls panic before calling `Assign` when it receives a `AssignedPartitions` and there aren't any committed starting offsets.  As the stack unwinds, a deferred function attempts to close the client.  That result in the process hanging, as `librdkafka` is waiting for the rebalance callback.

```
%7|1527435418.524|CGRPTERM|app#consumer-2| [thrd:main]: Group "app": waiting for rebalance_cb, 0 toppar(s), 0 unassignment(s), 0 commit(s) (state up, join-state wait-assign-rebalance_cb) before terminating
```

We got around it by calling `Assign(nil)` before calling panic to satisfy the callback demand.  But I would argue you should be able to terminate the client on demand without it hanging.

**Closed** 2019-10-17 07:51 UTC
Labels: bug, try reproduce
