### ISSUE TITLE
Unable to install using go get

### ISSUE THREAD

**Issue by abhaikollara** [confluentinc/confluent-kafka-go#583] opened 2021-01-11 10:15 UTC
Description
===========
Unable to install using `go get -u gopkg.in/confluentinc/confluent-kafka-go.v1/kafka`. I was following the instructions as per the readme for installation using `go get`. It failed like this

```
cannot find package "github.com/confluentinc/confluent-kafka-go/kafka/librdkafka" in any of:
	/usr/local/go/src/github.com/confluentinc/confluent-kafka-go/kafka/librdkafka (from $GOROOT)
	/home/my-username/go/src/github.com/confluentinc/confluent-kafka-go/kafka/librdkafka (from $GOPATH)
```

How to reproduce
================

```
go get -u gopkg.in/confluentinc/confluent-kafka-go.v1/kafka
```

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-go and librdkafka version (`LibraryVersion()`): Not sure how to fetch librdkafka version. Any help there would be appreciated
 - [ ] Apache Kafka broker version:
 - [ ] Client configuration: `ConfigMap{...}`:
 - [x] Operating system: **Linux Mint 20**
 - [ ] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts:
 - [ ] Critical issue

**Comment by edenhill** [comment] 2021-01-11 10:25
Recommend you use go modules instead

**Comment by hdeveer** [comment] 2021-01-12 09:47
I have the same issue on FreeBSD (12.1).
I found out that making a symlink in: ~/go/src/github.com/confluentinc/confluent-kafka-go/kafka
with: ln -s librdkafka_vendor librdkafka
does work?
(PS I even don't understand how to use go modules, because I tried a lot of things and nothing works).

**Comment by ackey-tah** [comment] 2021-01-14 01:49
I have the same issue.

The package folder "github.com/confluentinc/confluent-kafka-go/kafka/**librdkafka**" has been changed to 
"github.com/confluentinc/confluent-kafka-go/kafka/**librdkafka_vendor**".

Can someone please put it back?

**Comment by newcarrotgames** [comment] 2021-01-15 14:06
@hdeveer  I believe @edenhill means import the package `github.com/confluentinc/confluent-kafka-go/kafka` which supports go modules instead of `gopkg.in/confluentinc/confluent-kafka-go.v1/kafka`. _I think_ the gopkg.in package is meant for vendored builds. I'm not 100% sure though, so hopefully the devs here can confirm/deny this.

**Comment by hdeveer** [comment] 2021-01-15 14:19
I tried both paths as import, both give similar errors. As far as I know gopkg.in paths are only used to make redirects to the real implementation?
With go modules the module is automatically loaded from the go.mod dependency file as I understood.

**Comment by cianfrocca** [comment] 2021-01-18 16:47
I just got the same error with a new project, but the OP's instructions worked perfectly just a few months ago, so something just chnaged recently. I notice that the path github.com/confluentinc/confluent-kafka-go/kafka/librdkafka now doesn't exist. Rather, there is a path github.com/confluentinc/confluent-kafka-go/kafka/librdkafka_vendor.

**Comment by cianfrocca** [comment] 2021-01-18 16:52
Following up... if i mv the librdkafka_vendor path to librdkafka, everything works as before. I hate doing this, obviously confluent made the change for a reason. Hoping for an explanation...

**Comment by hdeveer** [comment] 2021-01-18 17:02
@cianfrocca Indeed it has worked for me some while ago too, so must be some regression issue. Instead of moving it I created a symlink, also not nice, but better then renaming the directory which may cause conflicts when updating it. With a symlink you only remove the link are are back to the original.

**Closed** 2022-03-18 19:49 UTC
