### ISSUE TITLE
malformed DWARF TagVariable entry

### ISSUE THREAD

**Issue by tonggt** [confluentinc/confluent-kafka-go#1147] opened 2024-03-06 02:59 UTC
Description
===========
GoLang version: 1.13
Confluent Kafka version: github.com/confluentinc/confluent-kafka-go v1.9.1
OS: Mac 14.1.1 

# github.com/confluentinc/confluent-kafka-go/kafka
malformed DWARF TagVariable entry

How to reproduce
================
Just importing the confluent kafka library and building a project throws this error.

Checklist
=========
Please provide the following information:

 - [y] confluent-kafka-go and librdkafka version (`LibraryVersion()`):
 - [ ] Operating system:Mac 14.1.1

**Comment by milindl** [comment] 2024-03-09 03:37
Hi, do you get the same error with the latest version (2.3.0) on a version of go 1.17+ ?

**Comment by tonggt** [comment] 2024-03-11 03:50
> Hi, do you get the same error with the latest version (2.3.0) on a version of go 1.17+ ?
But our project need in go1.13, and I find is okay when  GoLang version: 1.21.3

**Comment by milindl** [comment] 2024-03-12 14:25
Hi @tonggt , go 1.13 has been unsupported for almost 3.5 years. It seems to me that the issue is from go itself, this issue: https://github.com/golang/go/issues/53000 . Hence, I think updating go version might be needed, and this isn't something we can fix.

**Comment by tonggt** [comment] 2024-03-13 02:54
> Hi @tonggt , go 1.13 has been unsupported for almost 3.5 years. It seems to me that the issue is from go itself, this issue: [golang/go#53000](https://github.com/golang/go/issues/53000) . Hence, I think updating go version might be needed, and this isn't something we can fix.

Alright, I will try other ways, thanks a lot!!!

**Comment by milindl** [comment] 2024-03-13 05:34
You're welcome, closing this issue.

**Closed by milindl** 2024-03-13 05:34 UTC
