### ISSUE TITLE
Resolving InvalidTimestampException with Confluent-Kafka-Go v2.1.0 and Kafka v3.2.1

### ISSUE THREAD

**Issue by Howard0401** [confluentinc/confluent-kafka-go#988] opened 2023-04-24 18:17 UTC
Description
===========

I'd like to ask if anyone has encountered the following issue when using confluent-kafka-go v2.1.0 to connect to a Kafka v3.2.1 server:  A particular topic on the Kafka server logs an INFO message stating "starts at leader epoch," after about half an hour,  followed by an InvalidTimestampException error that says "One or more records have been rejected due to invalid timestamp", which cause high CPU usage for the one of three brokers.

like this:

```
Removed fetcher for partitions Set({My_Topic}) Stopped fetchers as part of LeaderAndIsr request correlationId 293 from controller 0 epoch 3 as part of the become-leader transition for 1 partitions

Loading producer state till offset 0 with message format version 2

Created log for partition {My_Topic} in /var/lib/kafka/{My_Topic} with properties {}

[Partition {My_Topic} broker=2] No checkpointed highwatermark is found for partition {My_Topic}

[Partition {My_Topic} broker=2] Log loaded for partition {My_Topic} with initial high watermark 0

Leader {My_Topic} starts at leader epoch 0 from offset 0 with high watermark 0 ISR [2,1,0] addingReplicas [] removingReplicas []. Previous leader epoch was -1. 
```

And this:
`
Error processing append operation on partition {My_Topic} org.apache.kafka.common.errors.InvalidTimestampException: One or more records have been rejected due to invalid timestamp`

**This error might occur after upgrading confluent-kafka-go to v2, too**, and I haven't found any commit addressing valid message timestamp issues when comparing the source code before and after the upgrade. There seems to be a parameter related to the timestamp and leader epoch, but the Kafka server's code only reports the aforementioned error when verifying memory record messages. I've been pondering this issue for a while and still don't understand it, so I hope someone can help clarify.

How to reproduce
================
It's possible that producing a large number of messages for this topic could be the issue, but I'm not certain.

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-go and librdkafka version (` confluent-kafka-go v1.8.2`):

 - [x] Apache Kafka broker version:  Kafka 3.2.1

 - [x] Client configuration: `ConfigMap{...}`
```KAFKA_HEAP_OPTS 
// it should be 6~8G?
Xmx4G -Xms4G -XX:MetaspaceSize=96m -XX:G1HeapRegionSize=16M
                -XX:MinMetaspaceFreeRatio=50 -XX:MaxMetaspaceFreeRatio=80
// and what configs are required to provide?                
```
 - [x] Operating system: Linux (k8s statefulset 4 Core, 8G Ram limit), but did not encounter this problem after upgrade to 8 Core, 12G RAM limit
 
 - [x] Provide broker log excerpts
 ```
Removed fetcher for partitions Set({My_Topic}) Stopped fetchers as part of LeaderAndIsr request correlationId 293 from controller 0 epoch 3 as part of the become-leader transition for 1 partitions

Loading producer state till offset 0 with message format version 2

Created log for partition {My_Topic} in /var/lib/kafka/{My_Topic} with properties {}

[Partition {My_Topic} broker=2] No checkpointed highwatermark is found for partition {My_Topic}

[Partition {My_Topic} broker=2] Log loaded for partition {My_Topic} with initial high watermark 0

Leader {My_Topic} starts at leader epoch 0 from offset 0 with high watermark 0 ISR [2,1,0] addingReplicas [] removingReplicas []. Previous leader epoch was -1. 

Error processing append operation on partition {My_Topic} org.apache.kafka.common.errors.InvalidTimestampException: One or more records have been rejected due to invalid timestamp
```
 - [x] Critical issue

**Comment by milindl** [comment] 2023-05-15 09:29
Hi @Howard0401 , could you please try reproducing the same issue with debug logs? You can use the config property, "debug", and set it to "all", if possible. 
Also, I would recommend trying with v2.1.1, even though there is nothing specifically addressing this issue, there are a lot of changes around epoch handling due to the implementation of KIP-320.

**Comment by Howard0401** [comment] 2023-06-13 08:54
Hi @milindl,   

I found the root cause: the high CPU usage at 100% for a long time may be causing a large number of messages with invalid timestamps...

There doesn't seem to be a strong relationship between the version of Kafka and confluent-kafka-go.

The issue is that Kafka only uses log4j, but our server has a custom log4j2.xml file that overwrites some of Kafka's log paths...

[https://bugs.openjdk.org/browse/JDK-8222942](https://bugs.openjdk.org/browse/JDK-8222942)

**Comment by milindl** [comment] 2024-02-13 13:20
Closing this - please reopen if the issue still persists (and is happening unrelated to the broker sending invalid messages at high CPU usage). Thanks

**Closed by milindl** 2024-02-13 13:20 UTC
Labels: wait info
