### ISSUE TITLE
Consumer crashes with assert: rkbuf->rkbuf_rkb

### ISSUE THREAD

**Issue by wjbergin** [confluentinc/confluent-kafka-go#650] opened 2021-05-28 14:38 UTC
Description
===========
The Confluent Kafka Go client was added to a service to consume messages. Occasionally on startup, after the consumer is created and starts consuming messages the service crashes and logs 
`*** rdkafka_request.c:219:rd_kafka_buf_read_topic_partitions: assert: rkbuf->rkbuf_rkb ***`. 
That's the only statement logged even with the debug level set to `all`. After a few crashes it eventually starts running without issue.  

Consumer configuration:
```
config := kafka.ConfigMap{      
    "go.application.rebalance.enable":    false,
    "bootstrap.servers":                           <broker list>,
    "group.id":                                          <consumer group>,
    "auto.offset.reset":                             "earliest",
    "partition.assignment.strategy":        "roundrobin",
    "debug":                                              "all",
   "ssl.certificate.location":                     <cert path>,
   "ssl.key.location":                                <key path>,
}
```

How to reproduce
================
Unable to reproduce as I'm not sure what's causing the issue, and it only happens occasionally.

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-go and librdkafka version (`LibraryVersion()`): 1.7.0 and the librdkafka version included with the module
 - [x] Apache Kafka broker version: 2.2.1
 - [x] Client configuration: `ConfigMap{...}` See above
 - [x] Operating system: Debian Buster
 - [x] Provide client logs (with `"debug": ".."` as necessary)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by jd78** [comment] 2021-06-08 07:48
I'm having the same issue and I can reproduce it easily even using a local docker cluster. Just start a consumer with another library (kafka-go for example), then start a confluent consumer using the same broker/topic/consumer group. 
Just note that this does not happen only with v 1.7.0 but, at least, also with 1.6.1.

**Comment by edenhill** [comment] 2021-06-08 08:23
Sounds like it might be a consumer group metadata parsing issue.
Could you prepare a docker image that fully reproduces the problem?
Thanks

**Comment by jd78** [comment] 2021-06-08 10:52
[confluent-crash.zip](https://github.com/confluentinc/confluent-kafka-go/files/6615865/confluent-crash.zip)

Hi @edenhill, please see the attached package that should contain all you need to reproduce it. Many thanks.

**Comment by wjbergin** [comment] 2021-06-08 21:34
@jd78 Interesting find. I also have services using another client. Was looking into this one, to see if it handled connection issues better than the others.

**Comment by jd78** [comment] 2021-06-08 21:38
In my opinion confluent is the best (and probably only) library that should be used in golang. We are migrating now to confluent but the deploy to prod is quite a mess because of this issue as I need to kill all the running instances before deploying the new version using confluent.

**Comment by wjbergin** [comment] 2021-06-08 21:42
@jd78 And after all your instances are deployment, have you seen this issue again?

**Comment by jd78** [comment] 2021-06-08 21:47
@wjbergin nope, it’s super stable.

**Comment by edenhill** [comment] 2021-06-09 13:29
Wow, thanks for the repro @jd78 ! Will check it out later this week.

**Comment by edenhill** [comment] 2022-01-19 09:57
@thomaslee Thanks for the analysis and proposed fix :+1:

**Comment by edenhill** [comment] 2022-01-19 09:57
We'll ship a fix for this in the upcoming v1.9.0 release.

**Comment by alan-delrio** [comment] 2022-02-07 05:59
if this issue has been open since May, 2021 what have been the alternative for developing go clients since then? I most of the time get this error on the consumers we are developing. I guess we will just continue with https://github.com/segmentio/kafka-go

**Comment by edenhill** [comment] 2022-02-07 08:00
We're looking to release v1.9.0 within a couple of weeks.

**Closed by edenhill** 2022-02-07 08:00 UTC
Labels: bug

**Comment by alan-delrio** [comment] 2022-02-07 17:17
Tried with  confluent kafka-go v1.5, I get not rkbuf->rkbuf_rkb but all messages I get are nil, expect the partition assigned message @edenhill what is best tag release known to work well?

**Comment by alan-delrio** [comment] 2022-02-07 20:44
Alternative is use downgrade  v1.4.2 (May 07, 2020), how come this has been here that long. 

@wjbergin how have you been dealing with this bug all this time?
