### ISSUE TITLE
admin client go logs

### ISSUE THREAD

**Issue by ORESoftware** [confluentinc/confluent-kafka-go#1127] opened 2024-01-14 03:49 UTC
This patterns works fine for regular clients, but for the admin client, it spits out a bunch of noise/nonsense.

```golang
			chanLogs := make(chan kafka.LogEvent)

			defer func() {
				close(chanLogs)
			}()

			go func() {
				for {
					 logEv := <-chanLogs
					 vibelog.Stdout.Info("kafka admin -", logEv)
				}
			}()

			adminClient, err := kafka.NewAdminClient(&kafka.ConfigMap{
				"bootstrap.servers": cfg.KAFKA_BOOTSTRAP_SERVERS,
				"go.logs.channel":        chanLogs,
				"go.logs.channel.enable": true,
			})
```

This seems to behave differently than a non-Admin client ^^

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-go and librdkafka version (`LibraryVersion()`):
 - [x] Apache Kafka broker version: image: confluentinc/cp-kafka:latest
 - [x] Client configuration: `ConfigMap{...}`
 - [x] Operating system: MacOS
 - [x] Provide broker log excerpts
 - [x] Critical issue

**Comment by amills-vibeirl** [comment] 2024-01-15 22:36
nevermind, this issue was already addressed here - https://github.com/confluentinc/confluent-kafka-go/issues/1119#issuecomment-1869624426

**Comment by milindl** [comment] 2024-02-13 12:36
Closing this since it's a duplicate of #1119 , will fix and address that. There's a workaround provided in that issue.

**Closed by milindl** 2024-02-13 12:36 UTC
