### ISSUE TITLE
cgo: malformed DWARF TagVariable entry

### ISSUE THREAD

**Issue by dharani-sengunthar** [confluentinc/confluent-kafka-go#1112] opened 2023-12-07 14:29 UTC
Description
===========
GoLang version: 1.18
Confluent Kafka version: github.com/confluentinc/confluent-kafka-go/v2 v2.3.0
OS: Mac Ventura 13.5.2

When using a go build command getting an error
```
# github.com/confluentinc/confluent-kafka-go/v2/kafka
cgo: malformed DWARF TagVariable entry
```

How to reproduce
================
Just importing the confluent kafka library and building a project throws this error.

Checklist
=========
Please provide the following information:

 - [ y] confluent-kafka-go and librdkafka version (`LibraryVersion()`):
 - [ ] Operating system: Mac Ventura 13.5.2

**Comment by nithin-p-m** [comment] 2023-12-21 05:30
Try updating to go1.18.10. This resolved the issue for me. 
https://github.com/golang/go/issues/57044 is released in https://www.gitclear.com/open_repos/golang/go/release/go1.18.10

**Comment by milindl** [comment] 2024-03-20 12:06
@nithin-p-m is correct, the issue is within go itself. Closing this. Please reopen if this reoccurs in recent go versions.

**Closed by milindl** 2024-03-20 12:06 UTC

**Comment by aniketgawade** [comment] 2024-06-19 03:08
@nithin-p-m thanks fixed my issue

**Comment by arvindbeam** [comment] 2024-08-06 03:56
> @nithin-p-m is correct, the issue is within go itself. Closing this. Please reopen if this reoccurs in recent go versions.

I got this same error 
github.com/confluentinc/confluent-kafka-go v1.9.3-RC3 // indirect
Using
go version go1.22.5 darwin/arm64
