### ISSUE TITLE
offsetsForTimes - Is this supported in the library 

### ISSUE THREAD

**Issue by chandradeepak** [confluentinc/confluent-kafka-go#35] opened 2017-01-19 01:57 UTC
the latest version of kafka supports retrieving offsets by timestamp. Is this supported by confluent kafka go.
Also confluent kafka go  whether supports storing time stamp as supported in new kafka java client . Please clarify.

i saw the kafka.Message seems it supports. 

https://kafka.apache.org/0101/javadoc/org/apache/kafka/clients/consumer/KafkaConsumer.html#offsetsForTimes(java.util.Map)

**Comment by edenhill** [comment] 2017-01-20 09:31
Duplicate of #14

**Closed by edenhill** 2017-01-20 09:31 UTC
