### ISSUE TITLE
go build -tags static failing on macOS: ld: unknown option: -Bstatic

### ISSUE THREAD

**Issue by tchap** [confluentinc/confluent-kafka-go#81] opened 2017-08-03 14:17 UTC
Hi,

I am trying to build my project using `confluent-kafka-go` with `-tags static` and I am getting

```
ld: unknown option: -Bstatic
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

It's macOS Sierra 10.12.6.

**Comment by edenhill** [comment] 2017-08-04 07:35
Thank you, will look into it.

**Comment by edenhill** [comment] 2017-08-09 11:59
Duplicate of #59

**Closed by edenhill** 2017-08-09 11:59 UTC
Labels: duplicate

**Comment by tchap** [comment] 2017-08-09 13:22
@edenhill I created a separate issue because I could see #59 mentioning `-Bstatic` in any way. But if you think that this issue will be fixed by fixing the other issue, no problem in closing this one...
